# Generated by Django 4.2.1 on 2023-05-28 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explorer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='explorer',
            name='identi',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Identificador'),
        ),
    ]
